SYNONYM_MAP = {
    # Volume-related
    "loud": "loud",
    "louder": "loud",
    "quiet": "quiet",
    "quieter": "quiet",
    "amplified": "loud",
    "strong": "loud",
    "soft": "soft",
    "softer": "soft",
    # Warmth/temperature
    "warm": "warm",
    "warmer": "warm",
    # Clarity
    "clear": "clear",
    "clearer": "clear",
    "crisp": "crisp",
    "crisper": "crisp",
    "clean": "clear",
    # Echo effects
    "echo": "echo",
    "echoing": "echo",
    "echoes": "echo",
    "echos": "echo",
    # Muffled sounds
    "muffled": "muffled",
    "muted": "muffled",
    "dampened": "muffled",
    "dull": "muffled",
    "muddy": "muffled",
    # Bass
    "bass": "bass",
    "bassy": "bass",
    "deep": "deep",
    "deeper": "deep",
    # Sharp/Bright
    "sharp": "sharp",
    "sharper": "sharp",
    "bright": "bright",
    "brighter": "bright",
    # Distance
    "distant": "distant",
    "far": "far",
    "far-away": "far",
    "close": "close",
    "closer": "close",
    # Metallic/Tinny
    "tinny": "tinny",
    "thin": "tinny",
    # Smooth
    "smooth": "smooth",
    "smoother": "smooth",
    # Church/Religious
    "church": "church",
    "church-like": "church",
    "cathedral": "church",
    "organ": "organ",
    "organ-like": "organ",
    # Distorted
    "distorted": "distorted",
    "distortion": "distorted",
}
